# Generated by Django 5.0.4 on 2024-04-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student_profile",
            name="phone_number",
            field=models.IntegerField(null=True),
        ),
    ]
